language: node_js
node_js:
  - '8.10'
script:
  - npm test
deploy:
  - provider: script
    script: deploy.sh $PROD_LAMBDA_NAME $PROD_LAMBDA_ROLE $PROD_S3_BUCKET $PROD_CLOUDFRONT_DISTRIBUTION_ID
    skip_cleanup: true
    on:
      branch: master

  - provider: script
    script: deploy.sh $STAGING_LAMBDA_NAME $STAGING_LAMBDA_ROLE $STAGING_S3_BUCKET $STAGING_CLOUDFRONT_DISTRIBUTION_ID
    skip_cleanup: true
    on:
      branch: staging
