name: Deploy router updates to staging
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Run lambda and invalidate cloudfront
    runs-on: ubuntu-latest    
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps: 
      - name: Setup node
        uses: actions/setup-node@v1
        with: 
            node-version: '10.x'
      - uses: actions/checkout@master
      # - name: test
      #   run: |
      #     npm install
      #     npm test
      - name: run deploy shell script
        env: 
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          ./deploy.sh ${{ secrets.STAGING_LAMBDA_NAME }} ${{ secrets.STAGING_LAMBDA_ROLE }} ${{ secrets.PROD_S3_BUCKET }}  ${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }}
          aws cloudfront create-invalidation --distribution-id ${{ secrets.STAGING_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
